services:
  whatsapp-summary-bot:
    build: .
    container_name: whatsapp-summary-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
      - ./data:/app/data
      - ./logs:/app/logs